# Начало
name = ('Dan')
print('My name is: Dan')
City = ('Perm')
print('My city is: Perm')


age = 21
print("My age is:", age)
# Конец

# Начало
my_motorbike = {
    'brand': 'Ducatti',
    'engine_vol': 2.0,
    'price': 200
}
print(my_motorbike)

other_motorbike = {
    'engine_vol': 2.0,
    'price': 200,
    'brand': 'Ducatti'
}

print(other_motorbike)

print(my_motorbike == other_motorbike)
print(id(my_motorbike) == id(other_motorbike))
# Конец
